#!/bin/bash

echo "🔧 Setting up production Supabase environment..."
echo ""
echo "Please get these values from your Supabase dashboard:"
echo "1. Go to: https://supabase.com/dashboard/project/mnjczhlwcnwipdbajwkj"
echo "2. Navigate to: Settings → API"
echo "3. Copy the following values:"
echo ""
echo "📋 Project URL (should look like: https://mnjczhlwcnwipdbajwkj.supabase.co)"
echo "🔑 anon public key (starts with eyJ...)"
echo "🔐 service_role secret key (starts with eyJ...)"
echo ""
echo "Once you have these values, run:"
echo "export SUPABASE_URL='your-project-url'"
echo "export SUPABASE_ANON_KEY='your-anon-key'"
echo "export SUPABASE_SERVICE_ROLE_KEY='your-service-role-key'"
echo ""
echo "Then test the connection with:"
echo "npm run test-supabase-connection"
